### ISSUE TITLE
Efi file is super large

### ISSUE THREAD

**Issue by senseiod** [mizkichan/uefi-unifont#1]
After compiling, the efi file is very large, there are 60MB, why is this problem?

**Comment by mizkichan** [comment]
Because this library converts each glyph in the font file into bitmaps. Each glyph has the size of 8x16 or 16x16 and 24-bit color (3 bytes) per pixel, and the number of glyphs is 65536. So the size of the converted font file is roughly 16*16*3*65536 = 50331648 = 48MB.
Building bitmap at compile time makes searching and drawing glyphs faster, but indeed the large size of a binary can be a problem. I'll try to fix it.

**Comment by senseiod** [comment]
Oh.Thank you. I understand now.


------------------------------------------------------------------
发件人：Mizuki HAGIMOTO <notifications@github.com>
发送时间：2019年9月21日(星期六) 17:24
收件人：mizkichan/uefi-unifont <uefi-unifont@noreply.github.com>
抄　送：周建国 <moyan@iouyi.top>; Author <author@noreply.github.com>
主　题：Re: [mizkichan/uefi-unifont] Efi file is super large (#1)

Because this library converts each glyph in the font file into bitmaps. Each glyph has the size of 8x16 or 16x16 and 24-bit color (3 bytes) per pixel, and the number of glyphs is 65536. So the size of the converted font file is roughly 16163*65536 = 50331648 = 48MB.
 Building bitmap at compile time makes searching and drawing glyphs faster, but indeed the large size of a binary can be a problem. I'll try to fix it.
